services:
  - type: web
    name: elpis-app
    env: node
    plan: free
    buildCommand: "cd interface/web && npm install --include=dev && npm run build && cd ../bridge && npm install"
    startCommand: "cd interface/bridge && node server.js"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        value: "mongodb+srv://Elpisdb:dbElpis12548256%40%7C%7B%23%7C@cluster0.j3pygdy.mongodb.net/?appName=Cluster0"
